[ENH] MNE Analyze loading bar
mne-tools/mne-cpp pull request #693
Opened 2020-09-09 16:33 UTC by gabrielbmotta

- Add loading bar widget to status bar.
- Moved detect trigger to separate thread to prevent freeze/stutter.
- Detecting events from triggers now triggers loading bar to appear during calculation.

2020-09-10 17:02 UTC, LorenzE requested changes
cool new feature! We need to think about how to handle multiple loading events send from different
plugins to the status bar. Any ideas @gabrielbmotta ?

2020-09-10 17:02 UTC, LorenzE commented on applications/mne_analyze/plugins/annotationmanager/annotationsettingsview.h
> +                                   double dThreshold);
mind indentation

2020-09-10 17:02 UTC, LorenzE commented on libraries/disp/viewers/triggerdetectionview.h
> +    QString getChannelName();
rename to `getSelectedStimChannel()`

2020-09-10 18:54 UTC, gabrielbmotta commented on applications/mne_analyze/plugins/annotationmanager/annotationsettingsview.cpp
> +        emit loadingEnd();
This is leftover from my attempt to implement this without QFuture. Will remove.

2020-09-10 19:20 UTC, gabrielbmotta commented on applications/mne_analyze/plugins/annotationmanager/annotationsettingsview.cpp
> +        QApplication::processEvents();
This is leftover from my attempt to implement this without QFuture. Will remove.

2020-09-10 19:40 UTC, gabrielbmotta commented
With multiple loads we could maybe have a loading stack where each new loadingStart adds an item to it, and only the most recent loading message gets diplayed, then while whichever one is the most recently received one is at the top, and items get popped of if they are done, with an item in the stack being marked done if they have received a corresponding loadingEnd.

2020-09-10 20:20 UTC, LorenzE commented
> With multiple loads we could maybe have a loading stack where each new loadingStart adds an item to it, and only the most recent loading message gets diplayed, then while whichever one is the most recently received one is at the top, and items get popped of if they are done, with an item in the stack being marked done if they have received a corresponding loadingEnd.

Or maybe we can have multiple loading bars displayed for every process currently running? Something like a drop down widget which shows all loading bars when selected.

2020-09-14 17:11 UTC, LorenzE commented
The name of the generated average model should include the name of the events group.

2020-09-14 17:13 UTC, LorenzE requested changes

2020-09-14 17:13 UTC, LorenzE commented on applications/mne_analyze/libs/anShared/Management/statusbar.cpp
> +void StatusBar::enterEvent(QEvent *event){
linebreak before {

2020-09-14 17:13 UTC, LorenzE commented on applications/mne_analyze/plugins/annotationmanager/annotationmanager.h
> +    void triggerLoadingStart(QString sMessage);
use `const QString&`

2020-09-14 17:13 UTC, LorenzE commented on applications/mne_analyze/plugins/annotationmanager/annotationmanager.h
> +
use `const QString&`

2020-09-14 17:40 UTC, gabrielbmotta commented
> The name of the generated average model should include the name of the events group.

![events](https://user-images.githubusercontent.com/34070103/93119472-db67f180-f68f-11ea-9c4f-8f3c4a4c58be.png)
Something like this?

2020-09-14 19:26 UTC, LorenzE commented
another thing: The detect from trigger channel for sample_audvis_raw.fif and trigger channel STI014 on MacOS did not produce any event groups (which it did before).

2020-09-14 19:30 UTC, gabrielbmotta commented
> another thing: The detect from trigger channel for sample_audvis_raw.fif and trigger channel STI014 on MacOS did not produce any event groups (which it did before).

Are the other channels working?

2020-09-14 20:38 UTC, LorenzE commented
> >

sry was on the wrong branch. works fine!

2020-09-15 15:15 UTC, LorenzE submitted a review, later dismissed

2020-09-15 15:45 UTC, LorenzE approved these changes

2020-09-15 15:54 UTC, merged