WIP [ENH] Event marking in real time
mne-tools/mne-cpp pull request #757
Opened 2021-01-25 17:01 UTC by gabrielbmotta

- Add Event and EventHandler classes
- Ability to add event with right click in RtFiffRawView
- Draw events based on window parameters and scrolling sample location

To do:
 - decide on/implement a way to save/export events
 - move event and event handler.

2021-02-04 16:37 UTC, juangpc commented
EventList is thought of to be a singleton?

2021-02-04 16:42 UTC, gabrielbmotta commented
> EventList is thought of to be a singleton?

In the way we conceptualized it to work with MNE Scan, we had EventList with a static list as a member variable. But in MNE Analyze we can have multiple EventLists, so instead of EventList being static internally, I changed it to that there is a regular list in EventList, but MNE Scan has a static EventList.

2021-02-04 16:44 UTC, gabrielbmotta commented
Removed the review request because it's not ready yet.

2021-03-20 11:54 UTC, gabrielbmotta commented
Thank you @juangpc

2021-04-05 17:02 UTC, LorenzE requested changes
Looks good! Very cool! Mostly cosmetic and questions. Can this file be deleted -> /tools/deployment/mne-cpp-windows-dynamic-x86_64.zip

2021-04-06 13:00 UTC, gabrielbmotta commented on applications/mne_analyze/libs/anShared/Model/eventmodel.cpp
> + * Copyright (C) 2020, Christoph Dinh, Lorenz Esch, Gabriel Motta, Juan Garcia-Prieto. All rights reserved.
This is annotationmodel.cpp renamed. Should it be considered a new file or do we keep its original header info?

2021-04-12 09:43 UTC, LorenzE commented on applications/mne_analyze/libs/anShared/Model/eventmodel.cpp
> + * Copyright (C) 2020, Christoph Dinh, Lorenz Esch, Gabriel Motta, Juan Garcia-Prieto. All rights reserved.
In this case you can leave the authors as is and update the month/year as well as the @since tag to when this file was renamed.

2021-04-16 18:53 UTC, juangpc commented on libraries/events/event.h
> +struct EVENTS_EXPORT Event
When I see a struct, I immediately know it is a small data container perhaps with some specific functionality in its constructor or/and in methods, but these will probably be short/fast/not very elaborated. So it resembles c's struct but not quite. I think this is a common practice. More expressive code.

2021-04-16 19:07 UTC, juangpc commented on libraries/events/event.h
> +namespace EVENTSINTERNAL {
I'm thinking about it now that you mention it. But I don't know: 
-I wan't to 'make it clear' to the user (another developer) of the class that THAT is internal dealing... abstracted... of the library. 
-I don't want to necessarily 'hide' it from the user. But maybe I should?

About 'internal' name... The namespaces are not nested. So I do want to keep 'internal to event library' thus,  EVENTSINTERNAL

Let me know what you think. (And thanks)

2021-04-18 18:15 UTC, LorenzE commented on libraries/events/event.h
> +namespace EVENTSINTERNAL {
I would try to hide code which is not part of the interface and thus not needed to work with the class from the dev completley. If possible I would even go as far as hiding internal code in anonymous namespaces in one translational unit. Latter is of course only possible if the code, which is to be hidden, is only used in one translational unit.

2021-04-18 18:22 UTC, LorenzE commented
Please remove the .zip file included in this PR.
Do you know why the checks are not starting? Maybe the conflict needs to be resolved first?

2021-04-26 21:30 UTC, juangpc commented on libraries/events/event.h
> +namespace EVENTSINTERNAL {
> What is the reasoning behind making the namespaces non-nested?

Initially we conceived the structure of having to separate ns but then export into the dll the "public" name. And leave the other "internal" one, not exported into the dll. But I'm now more inclined to cascade namespaces, after all it is in the name.

2021-04-27 14:51 UTC, juangpc commented on libraries/events/event.cpp
> +
done.

2021-04-27 14:51 UTC, juangpc approved these changes

2021-04-27 16:24 UTC, juangpc commented on libraries/events/event.h
> +namespace EVENTSINTERNAL {
namespaces are now nested.

2021-04-27 16:27 UTC, juangpc commented on applications/mne_analyze/libs/anShared/Model/eventmodel.cpp
> +                                 QObject* parent)
done.

2021-04-27 16:27 UTC, juangpc commented on applications/mne_analyze/libs/anShared/Model/eventmodel.cpp
> +//                return QVariant("Group");
nope.

2021-04-27 19:25 UTC, juangpc approved these changes

2021-04-27 19:28 UTC, gabrielbmotta commented on applications/mne_analyze/libs/anShared/Model/eventmodel.h
> +    typedef QSharedPointer<EventModel> SPtr;              /**< Shared pointer type for EventModel. */
I think I'd prefer to remain consistent with the other models. If we change to std pointers I think we should change all of the models, which might be best left to a future PR.

2021-04-27 19:34 UTC, juangpc commented
> Looks good! Very cool! Mostly cosmetic and questions. Can this file be deleted -> /tools/deployment/mne-cpp-windows-dynamic-x86_64.zip

Thanks! We deleted the zip file. And I think we're all set.

2021-04-28 11:54 UTC, LorenzE approved these changes
Very cool stuff!

2021-04-28 12:36 UTC, merged