[ENH, WIP] MNE_Analyze Dynamically reload plugins
mne-tools/mne-cpp pull request #782
Opened 2021-04-16 23:13 UTC by juangpc

Hi everybody,
This allows to, while the mne_analyze app is running, click a menu "Reload Plugins" and if a new dll is found in the plugin folder, the menus, views, controls will be loaded. 

- This is not WASM ready, I'm not sure how you could modify the plugin set during wasm execution.
- 

While doing this I noticed a few problems with the actual application itself, not directly related but I think my changes do improve the code. 
- PluginManager stores the plugins in a specific order given by a ```m_iOrder``` variable that works as a hint on what position you want your plugin to appear. Depending on which order you set this var to be, and what other plugins decide, your plugin will appear higher or lower in the menus. 
- Some warnings have been addressed. ✊🏻 
- If a plugin has already been loaded it will be not loaded again to the PluginManager list. 
- When data is loaded to the PluginManager there is new AbstractPlugin flag:```m_bInitialized``` flag that reflects that state.
- When the plugin has had its ```menus```, ```Controls``` and ```Views``` loaded to the menus of the application's window, there will be three member flags to show that: ```m_bMenuAlreadyLoaded```, ```m_bControlAlreadyLoaded``` and  ```m_bViewAlreadyLoaded ```.
- Added `.cpp` file to AbstractPlugin.
- MainWindow was a global object (within MNEANALYZE ns). It is now owned by AnalyzeCore, and there is a global pointer that gets intitialized and can be looking at MainWindow. This is used for the globalLogger.
- AnalyzeCore would previously give access to pluginmanager to the GUI. I see no reason why this should be the case, since these are two completely different things. So now MainWindow and PluginManager both communicate with their controller (AnalyzeCore). 
- I saw a few ```onThatEvent``` type of methods/slots... I think that we should try to adopt a more imperative style. The user (a gui, in this case, for instance) uses an api of another class... so you just use it. So not react to an event, just use the class you are supposed to use. (example: ```OnMainWindowClose``` -> ```close``` as in The gui uses the function ```close``` provided by the MainWindow Object).

- I solve a few tiny typo/style prblems in a few plugins.

Still a few things to do, like: 
-  Abstract Plugins could generate a leak of the created menu objects if ```getMenus()``` is called more than once.
-

2021-04-18 18:04 UTC, LorenzE requested changes
Just some minor comments

2021-04-18 18:04 UTC, LorenzE commented on applications/mne_analyze/mne_analyze/mainwindow.cpp
> +MainWindow::MainWindow(AnalyzeCore* pAnalyzeCore, QWidget *parent)
Our [coding conventions](https://mne-cpp.github.io/pages/development/contr_style.html) ask for aligning function parameters underneath each other.

2021-04-18 18:04 UTC, LorenzE commented on applications/mne_analyze/mne_analyze/mainwindow.cpp
> +#ifdef WASMBUILD
Please mind indentation of #ifdef just as you did above

2021-04-18 18:04 UTC, LorenzE commented on applications/mne_analyze/mne_analyze/mainwindow.cpp
> +    for(AbstractPlugin* pPlugin :m_pAnalyzeCoreController->getLoadedPlugins()) {
add one space after `:`

2021-04-18 18:04 UTC, LorenzE commented on applications/mne_analyze/mne_analyze/mainwindow.h
> +//}
can this be removed?

2021-04-18 18:04 UTC, LorenzE commented on applications/mne_analyze/mne_analyze/mainwindow.h
> +>>>>>>> d7cfc0499 (rename log structure mainwindow stores analyze core not pluginmanager)
Remove git conflict indicators

2021-04-19 18:24 UTC, gabrielbmotta reviewed
I'm running into an issue where the reloaded plugin's controls get added underneath the others instead of joining the stack of controls
![pluginload](https://user-images.githubusercontent.com/34070103/115284569-d6ce5480-a11a-11eb-80e1-c192f8dfd559.png)

2021-04-19 21:13 UTC, juangpc commented
Thanks for checking this out. Interesting. I'll research about it.

On Mon, Apr 19, 2021, 2:24 PM Gabriel Motta ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> I'm running into an issue where the reloaded plugin's controls get added
> underneath the others instead of joining the stack of controls
> [image: pluginload]
> <https://user-images.githubusercontent.com/34070103/115284569-d6ce5480-a11a-11eb-80e1-c192f8dfd559.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mne-tools/mne-cpp/pull/782#pullrequestreview-639173397>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACEKMICUACIPEQJCT4XTQOLTJRYOTANCNFSM43CML25A>
> .
>

2021-04-26 21:32 UTC, juangpc commented on applications/mne_analyze/libs/anShared/Management/pluginmanager.cpp
> +    for(AbstractPlugin*& plugin : m_qVecPlugins)
Agree, but I'd like to leave it as is. The addition of the reference just makes the compiler deal with references and avoids a warning.

2021-04-27 14:55 UTC, juangpc commented on applications/mne_analyze/libs/anShared/Plugins/abstractplugin.h
> +>>>>>>> 0ecfd5a34 (define qabstractplugin methods as non virtual when there is no need for that)
done

2021-04-27 16:06 UTC, juangpc reviewed
I think we've addressed all the comments.

2021-04-27 19:35 UTC, gabrielbmotta approved these changes

2021-04-30 14:51 UTC, LorenzE commented on applications/mne_analyze/libs/anShared/Management/pluginmanager.cpp
> +    for(AbstractPlugin*& plugin : m_qVecPlugins)
is there also a warning for `atuo&`

2021-04-30 14:53 UTC, LorenzE approved these changes
sry I totally forgot about this.

2021-04-30 16:44 UTC, merged